### ISSUE TITLE
改了檔名沒改 import 的名稱～

### ISSUE THREAD

**Issue by rich2020s** [chachachater/foodmap#14]
https://github.com/chachachater/foodmap/blob/d07977ce0303ae72406e9f1bee60b0ca10f58802/src/components/Form/Form.js#L14
應該是 "./FormStyle"
居然不能直接留言在上面！只好開 issue 了。或是有人要教我怎麼留言在 import 的那個部份裡面。

**Comment by chachachater** [comment]
悠悠解了👍
